version: "3"
services:
  develop:
    build: .
    ports:
      - "3600:3600"
    container_name: gfw-quicc-alerts-api-develop
    environment:
      PORT: 3600
      NODE_PATH: app/src
      CT_REGISTER_MODE: auto
      NODE_ENV: dev
      CARTODB_USER: wri-01
      API_GATEWAY_URL: http://192.168.99.100:8000
    command: develop
    volumes:
      - ./app:/opt/gfw-quicc-alerts-api/app
