version: "3"
services:
  test:
    build: .
    ports:
      - "3600"
    container_name: gfw-quicc-alerts-api-test
    environment:
      PORT: 3600
      NODE_PATH: app/src
      NODE_ENV: test
      CT_URL: http://mymachine:9000
      API_VERSION: v1
      CT_REGISTER_MODE: auto
    command: test
