prod:
  image: vizzuality/gfw-quicc-alerts-api:1.0.0${STAGING}
  ports:
    - "3600"
  env_file:
    - prod.env
  command: start
  restart: always
  log_driver: "syslog"
  log_opt:
    syslog-address: ${SYSLOG_ADDRESS}
    tag: gfw-quicc-alerts-api${STAGING}

