version: "3"
services:
  develop:
    build: .
    ports:
      - "3605:3605"
    container_name: gfw-quicc-alerts-api-develop
    environment:
      PORT: 3605
      NODE_PATH: app/src
      GATEWAY_URL: http://mymachine:9000
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      NODE_ENV: dev
      CARTODB_USER: wri-01
      API_GATEWAY_URL: http://192.168.99.100:8000
      LOCAL_URL: http://127.0.0.1:3605
      FASTLY_ENABLED: "false"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"

    command: develop
    volumes:
      - ./app:/opt/gfw-quicc-alerts-api/app
